import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createHighlighter } from 'shiki';
import type { Problem } from '../src/types/problem.ts';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(
  here,
  '..',
  'src',
  'data',
  'problems-highlighted.ts'
);

const THEMES = ['github-dark', 'github-light'] as const;
const LANGS = ['python', 'javascript'] as const;

export async function highlightProblems(problems: Problem[]): Promise<void> {
  const highlighter = await createHighlighter({
    themes: [...THEMES],
    langs: [...LANGS],
  });

  const entries = problems
    .filter((p) => p.kind === 'code')
    .map((p) => {
      const code = (p as Extract<Problem, { kind: 'code' }>).code;
      const render = (lang: 'python' | 'javascript') => ({
        dark: highlighter.codeToHtml(code[lang], {
          lang,
          theme: 'github-dark',
        }),
        light: highlighter.codeToHtml(code[lang], {
          lang,
          theme: 'github-light',
        }),
      });
      return {
        id: p.id,
        python: render('python'),
        javascript: render('javascript'),
      };
    });

  highlighter.dispose();

  const body = `// AUTO-GENERATED by scripts/highlight-problems.ts. Do not edit by hand.
// Run \`npm run build\` (or the prebuild script) to regenerate.

export interface HighlightedProblem {
  id: string;
  python: { dark: string; light: string };
  javascript: { dark: string; light: string };
}

export const highlightedProblems: Record<string, HighlightedProblem> = {
${entries
  .map(
    (e) => `  ${JSON.stringify(e.id)}: ${JSON.stringify(e, null, 2)
      .split('\n')
      .map((l, i) => (i === 0 ? l : '  ' + l))
      .join('\n')},`
  )
  .join('\n')}
};
`;

  await writeFile(outPath, body, 'utf8');
  console.log(`[prebuild] wrote ${entries.length} highlighted problems.`);
}
